# https://docs.travis-ci.com/user/multi-os/
os:
  - linux
  - osx
# https://docs.travis-ci.com/user/languages/r
language: r
bioc_packages: msa
r:
  - oldrel
  - release
  - devel
# Mac OS R devel build URL is out of date, currently.
# https://travis-ci.community/t/672
matrix:
  exclude:
    - r: devel
      os: osx
cache: packages
script:
  - R CMD build .
  - R CMD check *tar.gz
  - ./inst/bin/demo.sh
  - ./inst/bin/demo_empty.sh
