# https://docs.travis-ci.com/user/languages/r
language: r
bioc_packages: msa
r:
  - oldrel
  - release
  - devel
  - bioc-devel
cache: packages
script:
  - R CMD build .
  - R CMD check *tar.gz
  - ./inst/bin/demo.sh
