#!/usr/bin/env Rscript

# CHIIMP command-line script.
#
# This will load chiimp from either an available library, or (if executed from
# within the package source directory) directly from the package source via
# devtools.
#
# In Linux this should be executable directly.  To use in Windows see
# chiimp.cmd.

# If called from package source, load from that
args <- commandArgs()
f <- gsub("^--file=", "", args[grep("^--file=", args)])
f <- normalizePath(f)
pkgpath <- dirname(dirname(f))
if ("inst" %in% list.files(pkgpath)) {
  suppressWarnings(devtools::load_all(pkgpath, quiet = TRUE))
}

results <- chiimp::main()
