# https://blog.jdblischak.com/posts/circleci-for-r-1/
# https://blog.jdblischak.com/posts/circleci-for-r-2/
# https://gitlab.irstea.fr/in-wop/airGRiwrm/-/issues/53
version: 2.1
jobs:
  build:
    docker: 
      - image: rocker/verse:4.1.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          # getting TeX font errors otherwise, when it tries to run Rd2pdf.
          command: R CMD check --no-manual *tar.gz
      - store_artifacts:
          name: "Store Artifacts: 00check.log"
          path: chiimp.Rcheck/00check.log
      - store_artifacts:
          name: "Store Artifacts: 00install.out"
          path: chiimp.Rcheck/00install.out
