# https://blog.jdblischak.com/posts/circleci-for-r-1/
# https://blog.jdblischak.com/posts/circleci-for-r-2/
version: 2.1
jobs:
  build:
    docker: 
      # https://gitlab.irstea.fr/in-wop/airGRiwrm/-/issues/53
      - image: rocker/tidyverse:4.1.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
      - run:
          name: Install package dependencies
          command: R -e "devtools::install_deps(dep = TRUE)"
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "DESCRIPTION" }}
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz
      - store_artifacts:
          name: "Store Artifacts: check log"
          path: chiimp.Rcheck/00check.out
      - store_artifacts:
          name: "Store Artifacts: install log"
          path: chiimp.Rcheck/00install.out
